// This macro allows to quantify the senescent-associated ß-galactosidase (SAßG) activity from brightfield images

mypath = File.openDialog("Select a file");
run("Set Measurements...", "area mean standard min centroid center perimeter shape feret's integrated median display redirect=None decimal=4");
open(mypath);
// run("Bio-Formats", "open=mypath autoscale color_mode=Default rois_import=[ROI manager] view=Hyperstack stack_order=XYCZT");
mydirectory = File.getDirectory(mypath);
filename = File.getNameWithoutExtension(mypath);
rawstack = getTitle();

// Here the pixel size is set according to the used setup
run("Set Scale...", "distance=1878 known=1000 unit=µm");
selectWindow(rawstack);
run("Duplicate...", " ");
duplicate = getTitle();

// Generate a "Results" folder at the path of the raw data
File.makeDirectory(mydirectory+"/Results/");

selectWindow(rawstack);


run("Gaussian Blur...", "sigma=1");
// run("Color Threshold...");
// Color Thresholder 2.9.0/1.53t
// Autogenerated macro, single images only!
min=newArray(3);
max=newArray(3);
filter=newArray(3);
a=getTitle();
run("HSB Stack");
run("Convert Stack to Images");
selectWindow("Hue");
rename("0");
selectWindow("Saturation");
rename("1");
selectWindow("Brightness");
rename("2");
min[0]=120;
max[0]=180;
filter[0]="pass";
min[1]=25;
max[1]=255;
filter[1]="pass";
min[2]=0;
max[2]=180;
filter[2]="pass";
for (i=0;i<3;i++){
  selectWindow(""+i);
  setThreshold(min[i], max[i]);
  run("Convert to Mask");
  if (filter[i]=="stop")  run("Invert");
}
imageCalculator("AND create", "0","1");
imageCalculator("AND create", "Result of 0","2");
for (i=0;i<3;i++){
  selectWindow(""+i);
  close();
}
selectWindow("Result of 0");
close();
selectWindow("Result of Result of 0");
rename(a);



run("Create Selection");
roiManager("Add");

selectWindow(rawstack);
run("Select None");
run("Analyze Particles...", "size=65-Infinity show=Outlines exclude add");

// Measure the "saturation" of the raw image which apparently correlates with the beta-gal. signal and activity
selectWindow(duplicate);
run("HSB Stack");
run("Convert Stack to Images");
selectWindow("Saturation");

nROIs = roiManager("count");
for (j = 1; j < nROIs; j++) {
roiManager("Select", newArray(0,j));
roiManager("AND");
run("Measure");
};

saveAs("Results", mydirectory+"/Results/"+filename+".csv");
roiManager("Deselect");
roiManager("Save", mydirectory+"/Results/"+filename+".zip");
selectWindow(rawstack);
saveAs("Tiff", mydirectory+"/Results/"+filename+"_Mask.tif");
selectWindow("Saturation");
saveAs("Tiff", mydirectory+"/Results/"+filename+"_SaturationQuant.tif");


roiManager("Deselect");
roiManager("Delete");
close("ROI Manager");
run("Close All");
close("Results");
